CREATE TABLE IF NOT EXISTS pump_series (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, description TEXT);
CREATE TABLE IF NOT EXISTS pump_models (id TEXT PRIMARY KEY, series_id TEXT NOT NULL REFERENCES pump_series(id), code TEXT NOT NULL UNIQUE, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS motors (id TEXT PRIMARY KEY, power_kw NUMERIC NOT NULL, voltage_v NUMERIC, phase INTEGER, frequency_hz NUMERIC, speed_rpm NUMERIC);
CREATE TABLE IF NOT EXISTS pump_configurations (id TEXT PRIMARY KEY, model_id TEXT NOT NULL REFERENCES pump_models(id), code TEXT NOT NULL UNIQUE, motor_id TEXT NOT NULL REFERENCES motors(id), seal TEXT, connection TEXT, materials_json TEXT NOT NULL DEFAULT '{}', weight_kg NUMERIC, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS dimensions (id TEXT PRIMARY KEY, configuration_id TEXT NOT NULL REFERENCES pump_configurations(id), length_mm NUMERIC, width_mm NUMERIC, height_mm NUMERIC, weight_kg NUMERIC);
CREATE TABLE IF NOT EXISTS performance_curves (id TEXT PRIMARY KEY, configuration_id TEXT NOT NULL REFERENCES pump_configurations(id), kind TEXT NOT NULL, unit TEXT NOT NULL, speed_rpm NUMERIC NOT NULL, frequency_hz NUMERIC NOT NULL, source_id TEXT);
CREATE TABLE IF NOT EXISTS curve_points (id TEXT PRIMARY KEY, curve_id TEXT NOT NULL REFERENCES performance_curves(id) ON DELETE CASCADE, q NUMERIC NOT NULL, value NUMERIC NOT NULL);
CREATE TABLE IF NOT EXISTS engineering_rules (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, kind TEXT NOT NULL, severity TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, parameters_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS source_references (id TEXT PRIMARY KEY, document_id TEXT NOT NULL, page INTEGER, table_name TEXT, region TEXT, excerpt TEXT);
CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, actor_id TEXT NOT NULL, timestamp TEXT NOT NULL, before_json TEXT, after_json TEXT);
CREATE TABLE IF NOT EXISTS selection_projects (id TEXT PRIMARY KEY, number TEXT NOT NULL UNIQUE, customer_name TEXT, customer_company TEXT, title TEXT, application TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_duty_points (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES selection_projects(id) ON DELETE CASCADE, label TEXT, q NUMERIC NOT NULL, head NUMERIC NOT NULL, efficiency NUMERIC, npshr NUMERIC, power_kw NUMERIC);
CREATE TABLE IF NOT EXISTS project_selections (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES selection_projects(id) ON DELETE CASCADE, configuration_id TEXT NOT NULL REFERENCES pump_configurations(id), selected_option_ids_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_model_series ON pump_models(series_id);
CREATE INDEX IF NOT EXISTS idx_configuration_model ON pump_configurations(model_id);
CREATE INDEX IF NOT EXISTS idx_curve_configuration ON performance_curves(configuration_id);
CREATE INDEX IF NOT EXISTS idx_curve_points_curve_q ON curve_points(curve_id,q);
CREATE INDEX IF NOT EXISTS idx_project_duty_project ON project_duty_points(project_id);