import type {Pool} from "pg";
import {randomUUID} from "node:crypto";
export type IngestionStore={jobs:Map<string,any>;candidates:Map<string,any>;approvals:Map<string,any>;pool?:Pool | undefined};
export function createIngestionStore(pool?:Pool | undefined):IngestionStore{return{jobs:new Map(),candidates:new Map(),approvals:new Map(),pool}};
export async function loadIngestion(store:IngestionStore){if(!store.pool)return;const q=store.pool;const j=await q.query('SELECT id,source_document_id AS "sourceDocumentId",source_name AS "sourceName",source_type AS "sourceType",status,created_at AS "createdAt",created_by AS "createdBy" FROM ingestion_jobs ORDER BY created_at DESC');const c=await q.query('SELECT id,job_id AS "jobId",payload_json,confidence,status,sources_json,conflicts_json,scope,created_at AS "createdAt" FROM ingestion_candidates ORDER BY created_at DESC');const a=await q.query('SELECT id,candidate_id AS "candidateId",approved_by AS "approvedBy",approved_at AS "approvedAt",confirmation,approval_note AS "approvalNote" FROM approval_records ORDER BY approved_at DESC');store.jobs.clear();store.candidates.clear();store.approvals.clear();for(const x of j.rows)store.jobs.set(x.id,x);for(const x of c.rows)store.candidates.set(x.id,{...x,payload:JSON.parse(x.payload_json),sources:JSON.parse(x.sources_json),conflicts:JSON.parse(x.conflicts_json),scope:x.scope??"catalog"});for(const x of a.rows)store.approvals.set(x.id,x)}
export async function createIngestionJob(store:IngestionStore,input:{sourceDocumentId?:string;sourceName:string;sourceType:string;createdBy:string}){const id=randomUUID();const item={id,status:"draft",createdAt:new Date().toISOString(),...input};if(store.pool)await store.pool.query("INSERT INTO ingestion_jobs(id,source_document_id,source_name,source_type,status,created_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)",[id,item.sourceDocumentId??null,item.sourceName,item.sourceType,item.status,item.createdAt,item.createdBy]);store.jobs.set(id,item);return item}
export async function createCandidate(store:IngestionStore,input:{jobId:string;payload:unknown;confidence:number;sources:unknown[];conflicts:unknown[];scope?:"catalog"|"curve"|"dimensions"|"project"|"full"}){if(!store.jobs.has(input.jobId))throw new Error("jobId does not exist");const id=randomUUID();const item={id,...input,scope:input.scope??"catalog",status:"review",createdAt:new Date().toISOString()};if(store.pool)await store.pool.query("INSERT INTO ingestion_candidates(id,job_id,payload_json,confidence,status,sources_json,conflicts_json,scope,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,input.jobId,JSON.stringify(input.payload),input.confidence,item.status,JSON.stringify(input.sources),JSON.stringify(input.conflicts),item.scope,item.createdAt]);store.candidates.set(id,item);return item}
export async function approveCandidate(store:IngestionStore,candidateId:string,input:{approvedBy:string;confirmation:boolean;approvalNote?:string}){const c=store.candidates.get(candidateId);if(!c)throw new Error("Candidate not found");if(c.status!=="review")throw new Error("Candidate is not awaiting review");if(c.conflicts.length>0&&!input.confirmation)throw new Error("Unresolved conflicts require explicit confirmation");const id=randomUUID();const approvedAt=new Date().toISOString();const item={id,candidateId,...input,approvedAt};if(store.pool)await store.pool.query("INSERT INTO approval_records(id,candidate_id,approved_by,approved_at,confirmation,approval_note) VALUES($1,$2,$3,$4,$5,$6)",[id,candidateId,input.approvedBy,approvedAt,input.confirmation,input.approvalNote??null]);c.status="approved";const job=store.jobs.get(c.jobId);if(job)job.status="approved";store.approvals.set(id,item);return{candidate:c,approval:item}}

export async function updateCandidate(store:IngestionStore,candidateId:string,input:{payload?:unknown;conflicts?:unknown[];confidence?:number}){const c=store.candidates.get(candidateId);if(!c)throw new Error("Candidate not found");if(c.status!=="review")throw new Error("Only review candidates can be edited");if(input.payload!==undefined)c.payload=input.payload;if(input.conflicts!==undefined)c.conflicts=input.conflicts;if(input.confidence!==undefined)c.confidence=input.confidence;if(store.pool)await store.pool.query("UPDATE ingestion_candidates SET payload_json=$1,confidence=$2,conflicts_json=$3 WHERE id=$4",[JSON.stringify(c.payload),c.confidence,JSON.stringify(c.conflicts),candidateId]);return c}
