import type {Pool} from "pg";
import {randomUUID} from "node:crypto";
import {persistCatalogItem,recordAudit,type CatalogStore} from "./catalog-service";
import type {IngestionStore} from "./ingestion-service";
export type PublicationStore={pool?:Pool;publications:Map<string,any>};
export function createPublicationStore(pool?:Pool):PublicationStore{return{pool,publications:new Map()}};
export async function loadPublications(store:PublicationStore){if(!store.pool)return;const rows=await store.pool.query('SELECT id,candidate_id AS "candidateId",approved_record_id AS "approvedRecordId",published_by AS "publishedBy",published_at AS "publishedAt",entity_type AS "entityType",entity_id AS "entityId",created_entity AS "createdEntity",payload_json FROM ingestion_publications ORDER BY published_at DESC');store.publications.clear();for(const x of rows.rows)store.publications.set(x.id,{...x,payload:JSON.parse(x.payload_json)})}
export async function publishCandidate(ingestion:IngestionStore,publication:PublicationStore,catalog:CatalogStore,candidateId:string,input:{publishedBy:string;entityType:"pump_series"|"pump_model"|"motor"|"configuration";entityId?:string}){const c=ingestion.candidates.get(candidateId);if(!c)throw new Error("Candidate not found");if(c.status!=="approved")throw new Error("Candidate must be approved before publication");const approval=[...ingestion.approvals.values()].find(x=>x.candidateId===candidateId);if(!approval)throw new Error("Approval record not found");const id=input.entityId??randomUUID();
const payload={...(c.payload as any),id};
if(input.entityType==="pump_series")catalog.series.set(id,payload);
else if(input.entityType==="pump_model")catalog.models.set(id,payload);
else if(input.entityType==="motor")catalog.motors.set(id,payload);
else catalog.configurations.set(id,payload);
await persistCatalogItem(catalog,input.entityType==="pump_series"?"series":input.entityType==="pump_model"?"model":input.entityType==="motor"?"motor":"configuration",payload);const item={id,candidateId,approvedRecordId:approval.id,publishedBy:input.publishedBy,publishedAt:new Date().toISOString(),entityType:input.entityType,entityId:id,createdEntity:!input.entityId,payload};if(publication.pool)await publication.pool.query("INSERT INTO ingestion_publications(id,candidate_id,approved_record_id,published_by,published_at,entity_type,entity_id,created_entity,payload_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,candidateId,approval.id,item.publishedBy,item.publishedAt,item.entityType,item.entityId,item.createdEntity,JSON.stringify(c.payload)]);publication.publications.set(id,item);recordAudit(catalog,{id:randomUUID(),entityType:item.entityType,entityId:item.entityId,action:"publish_from_ingestion",actorId:input.publishedBy,timestamp:item.publishedAt,after:payload});return item}
