import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";
type Series={id:string;code:string;name:string;description?:string};
type Model={id:string;seriesId:string;code:string;name:string};
type Curve={id:string;kind:"head"|"efficiency"|"power"|"npsh";unit:string;speedRpm:number;frequencyHz:number;points:Array<{q:number;value:number}>};
type Option={id:string;kind:"material"|"seal"|"connection"|"impeller"|"accessory";code:string;name:string};
type Config={id:string;code:string;modelId:string;model?:Model|null;motor?:{id:string;powerKw:number;voltageV?:number;phase?:number;frequencyHz?:number;speedRpm?:number}|null;dimensions?:{lengthMm?:number;widthMm?:number;heightMm?:number;weightKg?:number}|null;seal?:string;connection?:string;materials?:Record<string,string>;options?:Option[];curves:Curve[]};
const API=(import.meta.env.VITE_API_URL??"http://localhost:4000").replace(/\/$/,"");
async function get<T>(path:string):Promise<T>{const r=await fetch(API+path);if(!r.ok)throw new Error(await r.text());return r.json()}
function App(){
const[step,setStep]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState("");
const[series,setSeries]=useState<Series[]>([]),[models,setModels]=useState<Model[]>([]),[configs,setConfigs]=useState<Config[]>([]);
const[selectedSeries,setSelectedSeries]=useState(""),[selectedModel,setSelectedModel]=useState(""),[configId,setConfigId]=useState("");
const[project,setProject]=useState({number:"PRJ-"+new Date().getFullYear()+"-001",customer:"",title:""}),[dutyPoints,setDutyPoints]=useState<Array<{q:number;head:number;label?:string}>>([{q:10,head:50,label:"Design Point"}]),[projectId,setProjectId]=useState("");
const[running,setRunning]=useState(false),[selectionResult,setSelectionResult]=useState<any>(null);
const selected=useMemo(()=>configs.find(x=>x.id===configId),[configs,configId]);
useEffect(()=>{Promise.all([get<Series[]>("/api/v1/catalog/series")]).then(([s])=>{setSeries(s);if(s[0])setSelectedSeries(s[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
useEffect(()=>{if(!selectedSeries){setModels([]);return}get<Model[]>("/api/v1/catalog/models?seriesId="+encodeURIComponent(selectedSeries)).then(m=>{setModels(m);setSelectedModel(m[0]?.id??"")}).catch(e=>setError(e.message))},[selectedSeries]);
useEffect(()=>{if(!selectedModel){setConfigs([]);return}get<Config[]>("/api/v1/catalog/configurations?modelId="+encodeURIComponent(selectedModel)).then(c=>{setConfigs(c);setConfigId(c[0]?.id??"")}).catch(e=>setError(e.message))},[selectedModel]);
async function saveProject(){const r=await fetch(API+"/api/v1/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({number:project.number,customerName:project.customer,title:project.title})});if(!r.ok)throw new Error(await r.text());const p=await r.json();setProjectId(p.id);return p}
async function saveDutyPoints(){let id=projectId;if(!id)id=(await saveProject()).id;for(const point of dutyPoints){const r=await fetch(API+"/api/v1/projects/"+id+"/duty-points",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(point)});if(!r.ok)throw new Error(await r.text())}}
if(loading)return <main><div className="panel"><h2>Loading company catalog…</h2></div></main>;
return <main><header><div><h1>Pump Selection</h1><p>Company Engineering Selection Portal</p></div><div className="project">Project <b>{project.number}</b></div></header>{error&&<div className="error">{error}</div>}<nav>{["Project","Pump","Configuration","Duty Point","Result"].map((x,i)=><button className={step===i+1?"active":""} onClick={()=>setStep(i+1)} key={x}>{i+1}. {x}</button>)}</nav>
{step===1&&<section className="panel"><h2>Project</h2><label>Project Number<input value={project.number} onChange={e=>setProject({...project,number:e.target.value})}/></label><label>Customer<input value={project.customer} onChange={e=>setProject({...project,customer:e.target.value})}/></label><label>Project Title<input value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/></label><button className="primary" onClick={async()=>{try{await saveProject();setStep(2)}catch(e){setError(e instanceof Error?e.message:"Failed to create project")}}}>Continue</button></section>}
{step===2&&<section className="panel"><h2>Select Pump</h2><div className="two"><label>Pump Series<select value={selectedSeries} onChange={e=>setSelectedSeries(e.target.value)}>{series.map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select></label><label>Pump Model<select value={selectedModel} onChange={e=>setSelectedModel(e.target.value)}>{models.map(m=><option key={m.id} value={m.id}>{m.code} — {m.name}</option>)}</select></label></div><div className="grid">{configs.map(c=><button className={"card "+(configId===c.id?"selected":"")} onClick={()=>{setConfigId(c.id);setStep(3)}} key={c.id}><div className="pumpImage">PUMP</div><h3>{c.model?.name??c.code}</h3><p>{c.code}</p><small>{c.motor?c.motor.powerKw+" kW":""} {c.options?.length?"• "+c.options.length+" valid options":""}</small></button>)}</div>{configs.length===0&&<p className="note">No catalog configurations are available for this model.</p>}</section>}
{step===3&&selected&&<section className="panel"><h2>Configuration {selected.code}</h2><p className="muted">Only components belonging to this pump configuration are shown.</p><div className="facts"><Fact k="Motor" v={selected.motor?selected.motor.powerKw+" kW":"—"}/><Fact k="Voltage" v={selected.motor?.voltageV?selected.motor.voltageV+" V":"—"}/><Fact k="Connection" v={selected.connection??"—"}/><Fact k="Seal" v={selected.seal??"—"}/><Fact k="Materials" v={selected.materials?Object.entries(selected.materials).map(([k,v])=>k+": "+v).join(", "):"—"}/><Fact k="Valid Options" v={selected.options?.map(o=>o.kind+": "+o.name).join(", ")||"—"}/><Fact k="Dimensions" v={selected.dimensions?((selected.dimensions.lengthMm??"—")+" × "+(selected.dimensions.widthMm??"—")+" × "+(selected.dimensions.heightMm??"—")+" mm"):"—"}/></div><Curve config={selected}q={dutyPoints[0]?.q??0}h={dutyPoints[0]?.head??0}/><button className="primary" onClick={()=>setStep(4)}>Continue to Duty Points</button></section>}
{step===4&&selected&&<section className="panel"><h2>Duty Points</h2><p className="muted">Enter all required operating points. The hydraulic engine validates the selected configuration against every point.</p>{dutyPoints.map((point,i)=><div className="two" key={i}><label>Label<input value={point.label??""} onChange={e=>setDutyPoints(ps=>ps.map((p,j)=>j===i?{...p,label:e.target.value}:p))}/></label><label>Flow<input type="number" min="0" value={point.q} onChange={e=>setDutyPoints(ps=>ps.map((p,j)=>j===i?{...p,q:Number(e.target.value)}:p))}/><span>m³/h</span></label><label>Head<input type="number" min="0" value={point.head} onChange={e=>setDutyPoints(ps=>ps.map((p,j)=>j===i?{...p,head:Number(e.target.value)}:p))}/><span>m</span></label>{dutyPoints.length>1&&<button onClick={()=>setDutyPoints(ps=>ps.filter((_,j)=>j!==i))}>Remove</button>}</div>)}<button onClick={()=>setDutyPoints(ps=>[...ps,{q:10,head:50,label:"Additional Point "+(ps.length+1)}])}>Add Duty Point</button><Curve config={selected}q={dutyPoints[0]?.q??0}h={dutyPoints[0]?.head??0}/><button className="primary" disabled={running||dutyPoints.some(p=>p.q<=0||p.head<=0)} onClick={async()=>{try{setRunning(true);await saveDutyPoints();const r=await fetch(API+"/api/v1/selections/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dutyPoints,constraints:{maxMotorLoadRatio:1,allowedConfigurationIds:[configId]},flowUnit:"m3/h"})});if(!r.ok)throw new Error(await r.text());const result=await r.json();setSelectionResult(result);const selectedCandidate=result.candidates?.find((x:any)=>x.configurationId===configId);if(!selectedCandidate)throw new Error("The selected configuration does not satisfy the duty point.");if(projectId){const sr=await fetch(API+"/api/v1/projects/"+projectId+"/selection",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({configurationId:configId,selectedOptionIds:selected?.options?.map(o=>o.id)??[],request:{dutyPoints,flowUnit:"m3/h",constraints:{maxMotorLoadRatio:1,allowedConfigurationIds:[configId]}}})});if(!sr.ok)throw new Error(await sr.text())}setStep(5)}catch(e){setError(e instanceof Error?e.message:"Selection failed")}finally{setRunning(false)}}}>{running?"Running hydraulic selection…":"Run Hydraulic Selection"}</button></section>}
{step===5&&selected&&<section className="sheet"><h2>Selection Results</h2><div className="panel"><h3>Deterministic Selection Engine</h3><p>Engine version: {selectionResult?.engineVersion??"—"}</p><p>Valid candidates: <b>{selectionResult?.candidates?.length??0}</b></p>{selectionResult?.warnings?.length>0&&<div className="warning">{selectionResult.warnings.map((w:string,i:number)=><div key={i}>{w}</div>)}</div>}{selectionResult?.candidates?.slice(0,5).map((candidate:any)=><div className="card selected" key={candidate.configurationId}><b>Configuration {candidate.configurationId}</b><div>Head: {candidate.dutyResults?.[0]?.availableHead?.toFixed?.(2)} m</div><div>Efficiency: {candidate.dutyResults?.[0]?.efficiency?.toFixed?.(1)??"—"}%</div><div>Absorbed Power: {candidate.dutyResults?.[0]?.powerKw?.toFixed?.(2)??"—"} kW</div><div>Motor Load: {candidate.dutyResults?.[0]?.motorLoadRatio!==undefined?(candidate.dutyResults[0].motorLoadRatio*100).toFixed(1)+"%":"—"}</div></div>)}</div><section className="sheet"><h2>Selection Sheet</h2><div className="sheetHead"><div className="pumpImage large">PUMP</div><div><h1>{selected.model?.name??selected.code}</h1><p>Configuration: <b>{selected.code}</b></p><p>Project: {project.number}</p></div></div><Curve config={selected}q={dutyPoints[0]?.q??0}h={dutyPoints[0]?.head??0}/><div className="facts"><Fact k="Motor" v={selected.motor?selected.motor.powerKw+" kW":"—"}/><Fact k="Connection" v={selected.connection??"—"}/><Fact k="Seal" v={selected.seal??"—"}/><Fact k="Dimensions" v={selected.dimensions?((selected.dimensions.lengthMm??"—")+" × "+(selected.dimensions.widthMm??"—")+" × "+(selected.dimensions.heightMm??"—")+" mm"):"—"}/><Fact k="Duty Points" v={dutyPoints.map(p=>p.q+" m³/h @ "+p.head+" m").join(" • ")}/></div><p className="warning">AI-Assisted Selection Notice: selections and project organization may use AI assistance and must be reviewed and verified by a qualified engineer before final approval, purchase, installation, or operation.</p><div className="actions"><button onClick={()=>window.print()}>Print</button>{projectId&&<button onClick={()=>window.open(API+"/api/v1/projects/"+projectId+"/selection-sheet","_blank")}>Open Server Selection Sheet</button>}<button onClick={()=>setStep(3)}>Edit Configuration</button></div></section>}</main>)}
function Fact({k,v}){return <div><b>{k}</b>{v}</div>}
function Curve({config,q,h}){const curve=config.curves.find(c=>c.kind==="head");if(!curve||curve.points.length<2)return <div className="note">No structured head curve is available for this configuration.</div>;const sorted=[...curve.points].sort((a,b)=>a.q-b.q),maxQ=Math.max(...sorted.map(p=>p.q),q,1),maxH=Math.max(...sorted.map(p=>p.value),h,1),w=620,H=280;const pts=sorted.map(p=>`${(p.q/maxQ)*w},${H-(p.value/maxH)*H}`).join(" ");const x=(q/maxQ)*w,y=H-(h/maxH)*H;return <div className="curve"><svg viewBox={`0 0 ${w} ${H}`}><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="4"/><line x1={x} y1={y} x2={x} y2={H} stroke="currentColor" strokeDasharray="6 5"/><line x1="0" y1={y} x2={x} y2={y} stroke="currentColor" strokeDasharray="6 5"/><circle cx={x} cy={y} r="7" fill="currentColor"/></svg><div>Duty Point: <b>{q} m³/h @ {h} m</b> • Curve: {curve.speedRpm} rpm / {curve.frequencyHz} Hz</div></div>}
createRoot(document.getElementById("root")!).render(<App/>);