import Fastify from "fastify";
import {selectionEngine,selectFromCatalog} from "@pumps/selection-engine";
import {evaluateRules} from "@pumps/selection-engine/rules";
import {createCatalogStore} from "@pumps/db/catalog-service";
import {createProjectStore} from "@pumps/db/project-service";
import {registerCatalogRoutes} from "./catalog-routes.js";
import {registerProjectRoutes} from "./project-routes.js";
const app=Fastify({logger:true});
const catalogStore=createCatalogStore();
const projectStore=createProjectStore();
registerCatalogRoutes(app,catalogStore);
registerProjectRoutes(app,projectStore);
app.get("/health",async()=>({status:"ok",service:"pumps-api",version:"0.3.0"}));
app.get("/api/v1/catalog/status",async()=>({status:"ready",source:"company-catalog",catalogLoaded:catalogStore.configurations.size>0,series:catalogStore.series.size,models:catalogStore.models.size,configurations:catalogStore.configurations.size}));
app.post("/api/v1/selections/preview",async(request,reply)=>reply.send(selectionEngine.select(request.body as any)));
app.post("/api/v1/selections/run",async(request,reply)=>{const body=request.body as any;const catalog=[...catalogStore.configurations.values()].map(c=>({id:c.id,modelId:c.modelId,motorId:c.motorId,curves:[...catalogStore.curves.values()].filter(x=>x.configurationId===c.id)}));return reply.send(selectFromCatalog(body.request??body,catalog))});
app.post("/api/v1/rules/evaluate",async(request,reply)=>reply.send(evaluateRules((request.body as any).context,(request.body as any).rules??[])));
app.get("/api/v1/metadata/curve-kinds",async()=>({items:["head","efficiency","power","npsh"]}));
app.listen({host:"0.0.0.0",port:Number(process.env.PORT??4000)}).catch(e=>{app.log.error(e);process.exit(1)});